### ISSUE TITLE
Oauth2 required for inserting contacts?

### ISSUE THREAD

**Issue by RickKukiela** [tableau-mkt/elomentary#62]
I'm trying to use this library to insert contacts from a customers contact form on their website. I'm following the example found here (importing contacts into Eloqua):
https://github.com/tableau-mkt/elomentary/blob/master/doc/customObjects/bulk.md

When I run my code, I get the following exception:

Fatal error: Uncaught Eloqua\Exception\RuntimeException: Client error response [status code] 401 [reason phrase] You are not authorized to make this request. [url] https://secure.p03.eloqua.com/API/bulk/2.0/contacts/imports in C:\Projects\SublymeCommerce\sublyme-lib\sublyme\vendor\tableau-mkt\elomentary\src\HttpClient\HttpClient.php on line 131

Do we need to use OAuth2 for this or do I just have something set wrong for my account?

**Comment by bllevy** [comment]
@SublymeRick you should not need Oauth2 for this library.

Be sure to verify that your account has the necessary privileges to utilize the API and import contacts.

**Comment by RickKukiela** [comment]
Thanks for getting back so quickly. I'm having the client look into that right now. They created this account for me to use and probably did not give it the necessary permissions.

**Comment by RickKukiela** [comment]
I'm still having trouble with this. The client has talked to support and they are being generally unhelpful. They provided this response:

1. If he is using username password, his username should be CompanyName\User.Name

2. If he's using an auth header, he should base64 encode "CompanyName\User.Name:password"

Once the API user updates the way they are logging in with their user name, it should resolve the issue they are experiencing.

Obviously I have no control over any of this. I'm using the example provided verbatim.

```
						$client = new \Eloqua\Client();
						$client->authenticate($eloConfig['site'], $eloConfig['user'], $eloConfig['password'], 'https://secure.p03.eloqua.com/API/Bulk');

						$mapping = array(
							'name'                    => 'Elomentary import into Eloqua',
							'identifierFieldName'     => 'C_EmailAddress',
							'isSyncTriggeredOnImport' => 'false',
							'fields'                  => array (
								'C_FirstName'    => '{{Contact.Field(C_FirstName)}}',
								'C_LastName'     => '{{Contact.Field(C_LastName)}}',
								'C_Title'        => '{{Contact.Field(C_Title)}}',
								'C_BusPhone'     => '{{Contact.Field(C_BusPhone)}}',
								'C_EmailAddress' => '{{Contact.Field(C_EmailAddress)}}',
							)
						);

                        // Some sample contacts
						$contacts = array (
							array (
								'C_FirstName'    => $_POST["firstName"],
								'C_LastName'     => $_POST["lastName"],
								'C_Title'        => $_POST["TITLE"],
								'C_BusPhone'     => $_POST["PHONE"],
								'C_EmailAddress' => $_POST["email"],
							),
						);

                        // Do the required steps for staging and downloading export file
						$bulkApi = $client->api('contacts')->bulk();  // Gets the bulk API connector
                        $bulkApi->imports();                          // Sets connector to 'import' mode.
						$bulkApi->map($mapping);                      // Sends setup/mapping array to Eloqua
                        $bulkApi->upload($contacts);                  // Upload content to Eloqua staging area
						$bulkApi->sync();                             // Sync uploaded files your contacts
						$bulkApi->status();                           // Check status until processing is finished
						$log = $bulkApi->log();                       // Retrieving processing log

						print_r($log);
```

I get the following exception thrown somewhere inside the `$bulkApi->map()` method. 

``` Fatal error: Uncaught Eloqua\Exception\RuntimeException: Client error response [status code] 401 [reason phrase] You are not authorized to make this request. [url] https://secure.p03.eloqua.com/API/bulk/2.0/contacts/imports in .... ```

Does anyone have any clues as to what I'm doing wrong or what settings, specifically I need to have the client enable for my account for this to work? I'm at a loss here.

**Comment by bllevy** [comment]
Hi @SublymeRick,

I'm not seeing anything wrong with the code you posted, so I believe this is related to your account permissions. In the Eloqua security settings (as shown below), there is a checkbox for whether a user or (in this case a group) can consume the Eloqua API -- this **may** be the culprit if it is not set for your account. Not 100% sure though. You may need to actually create a group with access to the API, and then set your user to a member of that group.

![image](https://user-images.githubusercontent.com/19394444/29838553-5dbb762c-8cb0-11e7-97f0-5e18b6f79b56.png)

According to the [Eloqua Bulk API Getting Started](http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/Developers/BulkAPI/Getting%20started/getting-started.htm) docs, you also want to make sure your account satisfies these requirements:

> In order to be able to interact with your Eloqua data, your account needs adequate permissions to access contact fields, secondary assets, and so on.

**Comment by RickKukiela** [comment]
@bllevy Yeah my bad. The problem was actually relating to my password. See when I logged into the test account they gave me the first time it made me reset my password. I didnt start on the code right away so when I did a week later I forgot that I had done that and was still using the credentials supplied in the email they sent me. Hours wasted because of this lol sorry for bugging you.

**Comment by bllevy** [comment]
@SublymeRick I'm glad it was something that could be solved! Don't sweat it. Best of luck and be sure to reach out if you run into any complications.
