### ISSUE TITLE
Adding a new contact and adding them to a segment

### ISSUE THREAD

**Issue by RickKukiela** [tableau-mkt/elomentary#64]
I'm using the bulk API to insert a new contact record when a visitor fills out a contact form on my clients website. This is working great. However, I cannot seem to figure out how I could add this contact to an existing "segment" in eloquoa after being added to the system.

Is there a way to do this via the API and specifically, using this library?

**Comment by ghost** [comment]
Read up on Sync Actions this might be what you're looking for.

http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#Developers/BulkAPI/Reference/Syncs/sync-actions.htm%3FTocPath%3DBulk%2520API%7CReference%7C_____5

**Comment by RickKukiela** [comment]
So how do I use this library to do that? I dont see anything in the docs that covers that section of the bulk api. I also cannot find anything in the source code that would allow me to do this, though I might just be missing it.

**Comment by bllevy** [comment]
Hi @SublymeRick, as @ozigindere-ntpx pointed out, sync actions sound like the right method for your use-case. 

Sync actions are to be included in the [import object mapping](http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#Developers/BulkAPI/Tutorials/Import.htm%3FTocPath%3DBulk%2520API%7CTutorials%7C_____2) step. 

So they are not necessarily outlined in this particular wrapper library, but bulk API supports the functionality.

**Comment by RickKukiela** [comment]
I figured it out!

You have to add this to the $mappings array (if you're following the example in the bulk api contact import section):

```
$mapping['syncActions'] = array(
	array(
		'action' => 'add',
		'destination' => '{{ContactList[2093]}}'
	)
);
```

**Comment by RickKukiela** [comment]
Honestly it was a total bitch to figure out how to get the ID of the contact list they wanted this added to. The interface over there does not provide a way to figure this out, without jumping through hoops and checking the address bar.... smh

**Comment by RickKukiela** [comment]
Thanks for this sweet library! Definitely helped me out a ton.
