### ISSUE TITLE
Active maintenance?

### ISSUE THREAD

**Issue by nterbogt** [tableau-mkt/elomentary#65]
Is this project still under active maintenance?
I would like to have some additional functionality and am wondering if this is worth investing time into? From my research, this hasn't really had anything done to it since Jun 2017.
Thanks.

**Comment by iamEAP** [comment]
Hey @nterbogt,

As you've seen, there isn't active development on this from our side at this time.  That being said, we make use of this quite a lot--I'm absolutely open to reviewing PRs and discussing potential architecture / design, if you've got something you'd like to add.

**Comment by nterbogt** [comment]
Thanks. I'll probably try to pull something together over the next few weeks/months.
